# Generated by Django 4.0.6 on 2022-07-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dits1', models.DecimalField(decimal_places=100, max_digits=100)),
                ('dist2', models.DecimalField(decimal_places=100, max_digits=100)),
                ('dist3', models.DecimalField(decimal_places=100, max_digits=100)),
                ('dist4', models.DecimalField(decimal_places=100, max_digits=100)),
            ],
        ),
    ]
