# Generated by Django 4.0.6 on 2022-07-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='dist2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='volume',
            name='dist3',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='volume',
            name='dist4',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='volume',
            name='dits1',
            field=models.FloatField(),
        ),
    ]
