# Generated by Django 4.0.6 on 2022-07-22 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_volume_dist2_alter_volume_dist3_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Volume',
        ),
    ]
